### ISSUE TITLE
Running under windows 

### ISSUE THREAD

**Issue by BENETNATH** [realchrisward/Physiology-Analysis-Tools#20]
Just to mention that the script has to run under python 3.9
Plus after the install, I had to run :
pip3 uninstall -y PyQt6 pyqt6-plugins PyQt6-Qt6 PyQt6-sip pyqt6-tools qt6-applications qt6-tools
pip3 install pyqt6-plugins pyqt6-tools qt6-applications qt6-tools PyQt6

working now with this requirements.txt

adi-reader==0.0.9
cffi==1.17.1
click==7.1.2
numpy==2.0.2
pandas==2.2.2
physiology_analysis_tools==0.0.9
pycparser==2.22
PyQt5==5.15.11
PyQt5-Qt5==5.15.2
PyQt5_sip==12.15.0
PyQt6==6.4.2
pyqt6-plugins==6.4.2.2.3
PyQt6-Qt6==6.4.3
pyqt6-tools==6.4.2.3.3
PyQt6_sip==13.8.0
pyqtgraph==0.13.7
PyQtWebEngine==5.15.7
PyQtWebEngine-Qt5==5.15.2
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
pytz==2024.2
qt6-applications==6.4.3.2.3
qt6-tools==6.4.3.1.3
scipy==1.13.1
six==1.16.0
tzdata==2024.1
XlsxWriter==3.2.0

**Comment by realchrisward** [comment]
are you running from the github source or did you install physioogy-analysis-tools from pip?

**Comment by BENETNATH** [comment]
running from pip.

**Comment by realchrisward** [comment]
@BENETNATH the current version 0.0.17 has been updated to use pyside6 instead of pyqt. the requirements have also been revised. do you still experience issues in getting it to run when installing via pip?

**Comment by realchrisward** [comment]
I'm assuming the current version has corrected this...we can reopen or create a new issue if you notice problems installing/running the software.

**Comment by BENETNATH** [comment]
Hi Chris,
I will give a try on a clean computer to check if that works from scratch. If anything happens bad, I'll update here :)
